# Generated by Django 3.2.14 on 2022-07-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220731_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='prispevok',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
