# Generated by Django 3.2.14 on 2022-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prispevok_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prispevok',
            name='description',
        ),
        migrations.AlterField(
            model_name='prispevok',
            name='body',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
